### ISSUE TITLE
None of the AMIs searched for in this module are public AMIs

### ISSUE THREAD

**Issue by thomashashi** [hashicorp-modules/network-aws#12]
Attempting to run [Provision a Best Practices HashiStack Cluster in AWS](https://github.com/thomashashi/terraform-guides/tree/master/infrastructure-as-code/hashistack/best-practices/terraform-aws) will fail with 

```sh
Error: Error refreshing state: 2 error(s) occurred:

* module.hashistack_aws.data.aws_ami.hashistack: 1 error(s) occurred:

* module.hashistack_aws.data.aws_ami.hashistack: data.aws_ami.hashistack: Your query returned no results. Please change your search criteria and try again.
* module.network_aws.data.aws_ami.hashistack: 1 error(s) occurred:

* module.network_aws.data.aws_ami.hashistack: data.aws_ami.hashistack: Your query returned no results. Please change your search criteria and try again.
```

in the `terraform plan` stage, because it uses this module, and none of the AMIs this module searches for are publicly available.

**Comment by bensojona** [comment]
These are public now

**Comment by rozcietrzewiacz** [comment]
It's happening again for several modules - please see https://github.com/hashicorp/vault-guides/issues/130
